apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: codegen3-0619
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen3-0619 
  name: codegen3-0619
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: codegen3-0619 
    weight: 100 
  wildcardPolicy: None
